export const members = {
    'osaka': {
        'Disco Twister': null,
        'Shield Buster': 3,
        'Not in Kansas': 2,
        'Plant Monster': 3,
        'Hissy Fit': 1,
        'Mellow Bellow': 6,
        'Ancient Curse': 2,
        'Spiders': 1,
        'Zest from Above': 2,
        'Magnetism': 5,
        'Fishaster': 1,
        'Shrink Ray': 3,
        'Electric Deity': 1,
        'Building Portal': 3,
        'B Movie Monster': 1,
        'Tentacle Vortex': 2,
        'Doomsday Quack': null,
        'Blizzaster': 1,
        'Comic Hand': 5,
        '16 Tons': 2,
        'Flying Vu Robot': 2,
        'Hands of Doom': 2,
        'Dance Shoes': 2,
        'Giant Rock Monster': 2
    },
    'scranton': {
        'Flying Vu Robot': 3,
        '16 Tons': 4,
        'Hands of Doom': 4,
        'Blizzaster': 2,
        'Comic Hand': 3,
        'Giant Rock Monster': 2,
        'Dance Shoes': 3,
        'B Movie Monster': 3,
        'Tentacle Vortex': 3,
        'Fishaster': 2,
        'Zest from Above': 2,
        'Magnetism': 7,
        'Shrink Ray': 2,
        'Electric Deity': 1,
        'Building Portal': 4,
        'Shield Buster': 4,
        'Disco Twister': 1,
        'Plant Monster': 4,
        'Not in Kansas': 1,
        'Hissy Fit': 2,
        'Mellow Bellow': 3,
        'Ancient Curse': 1,
        'Spiders': 3
    },
    'odins': {
        'Tentacle Vortex': 4,
        'Doomsday Quack': null,
        'B Movie Monster': 1,
        'Dance Shoes': 1,
        'Giant Rock Monster': 1,
        'Blizzaster': 3,
        'Comic Hand': 6,
        'Flying Vu Robot': 1,
        '16 Tons': 4,
        'Hands of Doom': 3,
        'Mellow Bellow': 2,
        'Ancient Curse': 1,
        'Spiders': 1,
        'Shield Buster': 3,
        'Disco Twister': 2,
        'Not in Kansas': 2,
        'Plant Monster': 3,
        'Hissy Fit': 1,
        'Shrink Ray': 4,
        'Electric Deity': 2,
        'Building Portal': 4,
        'Zest from Above': 2,
        'Magnetism': 4,
        'Fishaster': 2
    },
    'bedrock': {
        'Electric Deity': 2,
        'Building Portal': 2,
        'Shrink Ray': 4,
        'Magnetism': 6,
        'Zest from Above': 1,
        'Fishaster': 2,
        'Spiders': 1,
        'Mellow Bellow': 2,
        'Ancient Curse': 1,
        'Plant Monster': 2,
        'Not in Kansas': 2,
        'Hissy Fit': 1,
        'Shield Buster': 3,
        'Disco Twister': 1,
        'Dance Shoes': 1,
        'Giant Rock Monster': 2,
        'Blizzaster': 2,
        'Comic Hand': 5,
        '16 Tons': 3,
        'Flying Vu Robot': 1,
        'Hands of Doom': 2,
        'Tentacle Vortex': 3,
        'Doomsday Quack': null,
        'B Movie Monster': 3
    },
    'andrvill': {
        'Tentacle Vortex': 2,
        'Spiders': 1,
        'Mellow Bellow': 5,
        'Ancient Curse': 1,
        'B Movie Monster': 1,
        'Plant Monster': 3,
        'Hissy Fit': 2,
        'Shield Buster': 3,
        'Electric Deity': 1,
        'Building Portal': 2,
        'Giant Rock Monster': 1,
        'Shrink Ray': 3,
        'Blizzaster': 4,
        'Comic Hand': 5,
        'Magnetism': 4,
        'Zest from Above': 3,
        '16 Tons': 2,
        'Hands of Doom': 1
    },
    'tio': {
        'Magnetism': 8,
        'Zest from Above': 5,
        'Fishaster': 4,
        'Electric Deity': 4,
        'Building Portal': 6,
        'Shrink Ray': 4,
        'Plant Monster': 5,
        'Not in Kansas': 4,
        'Hissy Fit': 4,
        'Disco Twister': 2,
        'Shield Buster': 4,
        'Spiders': 3,
        'Mellow Bellow': 5,
        'Ancient Curse': 2,
        'Blizzaster': 3,
        'Comic Hand': 6,
        '16 Tons': 5,
        'Flying Vu Robot': 3,
        'Hands of Doom': 5,
        'Dance Shoes': 4,
        'Giant Rock Monster': 4,
        'B Movie Monster': 5,
        'Tentacle Vortex': 5,
        'Doomsday Quack': 1
    },
    'meloncello': {
        'Doomsday Quack': null,
        'Tentacle Vortex': 3,
        'B Movie Monster': 3,
        'Giant Rock Monster': 3,
        'Dance Shoes': null,
        'Hands of Doom': 3,
        'Flying Vu Robot': 2,
        '16 Tons': 3,
        'Comic Hand': 5,
        'Blizzaster': 4,
        'Spiders': 2,
        'Ancient Curse': 2,
        'Mellow Bellow': 6,
        'Hissy Fit': 4,
        'Not in Kansas': 2,
        'Plant Monster': 3,
        'Disco Twister': 1,
        'Shield Buster': 2,
        'Building Portal': 2,
        'Electric Deity': 1,
        'Shrink Ray': 4,
        'Fishaster': 1,
        'Magnetism': 6,
        'Zest from Above': 2
    },
    'casterly rock': {
        'Building Portal': 2,
        'Electric Deity': null,
        'Shrink Ray': 3,
        'Fishaster': null,
        'Magnetism': 5,
        'Zest from Above': 1,
        'Spiders': 2,
        'Ancient Curse': 4,
        'Mellow Bellow': 4,
        'Hissy Fit': 2,
        'Plant Monster': 3,
        'Not in Kansas': 2,
        'Shield Buster': 2,
        'Disco Twister': null,
        'Giant Rock Monster': null,
        'Dance Shoes': 1,
        'Hands of Doom': 2,
        'Flying Vu Robot': null,
        '16 Tons': 2,
        'Comic Hand': 4,
        'Blizzaster': 3,
        'Doomsday Quack': 2,
        'Tentacle Vortex': 4,
        'B Movie Monster': 2
    },
    'pimpim': {
        'Mellow Bellow': 6,
        'Ancient Curse': 4,
        'Spiders': 1,
        'Shield Buster': 1,
        'Disco Twister': 2,
        'Not in Kansas': 2,
        'Plant Monster': 2,
        'Hissy Fit': 1,
        'Shrink Ray': 2,
        'Electric Deity': 1,
        'Building Portal': 2,
        'Zest from Above': 2,
        'Magnetism': 5,
        'Fishaster': 1,
        'Tentacle Vortex': 4,
        'Doomsday Quack': 1,
        'B Movie Monster': 1,
        'Dance Shoes': 1,
        'Giant Rock Monster': 2,
        'Blizzaster': 4,
        'Comic Hand': 5,
        'Flying Vu Robot': 1,
        '16 Tons': 3,
        'Hands of Doom': 3
    },
    'wicks': {
        'Magnetism': 4,
        'Zest from Above': 1,
        'Fishaster': 1,
        'Electric Deity': 2,
        'Building Portal': 3,
        'Shrink Ray': 2,
        'Not in Kansas': 1,
        'Plant Monster': 3,
        'Hissy Fit': 1,
        'Shield Buster': 1,
        'Disco Twister': 1,
        'Spiders': null,
        'Mellow Bellow': 1,
        'Ancient Curse': null,
        'Blizzaster': 1,
        'Comic Hand': 3,
        '16 Tons': 2,
        'Flying Vu Robot': 2,
        'Hands of Doom': 3,
        'Dance Shoes': 2,
        'Giant Rock Monster': 1,
        'B Movie Monster': 1,
        'Tentacle Vortex': 2,
        'Doomsday Quack': null
    },
    'venom': {
        'Doomsday Quack': 1,
        'Tentacle Vortex': 9,
        'B Movie Monster': 7,
        'Giant Rock Monster': 6,
        'Dance Shoes': null,
        '16 Tons': 10,
        'Flying Vu Robot': 7,
        'Hands of Doom': 11,
        'Blizzaster': 6,
        'Comic Hand': 11,
        'Mellow Bellow': 12,
        'Ancient Curse': 5,
        'Spiders': 8,
        'Shield Buster': 9,
        'Disco Twister': 4,
        'Not in Kansas': 5,
        'Plant Monster': 9,
        'Hissy Fit': 8,
        'Shrink Ray': 6,
        'Electric Deity': 6,
        'Building Portal': 9,
        'Fishaster': 7,
        'Zest from Above': 8,
        'Magnetism': 11
    },
    'captain': {
        'B Movie Monster': 7,
        'Tentacle Vortex': 4,
        'Comic Hand': 8,
        'Blizzaster': 9,
        'Hands of Doom': 5,
        '16 Tons': 4,
        'Flying Vu Robot': 3,
        'Dance Shoes': 3,
        'Giant Rock Monster': 4,
        'Hissy Fit': 4,
        'Not in Kansas': 6,
        'Plant Monster': 4,
        'Disco Twister': 5,
        'Shield Buster': 5,
        'Spiders': 3,
        'Ancient Curse': 2,
        'Mellow Bellow': 7,
        'Magnetism': 10,
        'Zest from Above': 4,
        'Fishaster': 3,
        'Building Portal': 5,
        'Electric Deity': 3,
        'Shrink Ray': 5,
        'Doomsday Quack': 2
    },
    'lindseg': {
        'Giant Rock Monster': 1,
        'Dance Shoes': 4,
        'Hands of Doom': 2,
        'Flying Vu Robot': 2,
        '16 Tons': 3,
        'Comic Hand': 3,
        'Blizzaster': null,
        'Doomsday Quack': null,
        'Tentacle Vortex': 2,
        'B Movie Monster': 1,
        'Building Portal': 2,
        'Electric Deity': 1,
        'Shrink Ray': 1,
        'Fishaster': 1,
        'Magnetism': 2,
        'Zest from Above': 2,
        'Spiders': null,
        'Ancient Curse': 1,
        'Mellow Bellow': 1,
        'Hissy Fit': 1,
        'Plant Monster': 3,
        'Not in Kansas': null,
        'Shield Buster': 1,
        'Disco Twister': null
    },
    'sunny': {
        'Spiders': null,
        'Mellow Bellow': 3,
        'Ancient Curse': 1,
        'Not in Kansas': 1,
        'Plant Monster': 3,
        'Hissy Fit': 1,
        'Shield Buster': 1,
        'Disco Twister': 1,
        'Electric Deity': null,
        'Building Portal': 1,
        'Shrink Ray': 2,
        'Magnetism': 4,
        'Zest from Above': 1,
        'Fishaster': 1,
        'Tentacle Vortex': 2,
        'Doomsday Quack': 2,
        'B Movie Monster': 3,
        'Dance Shoes': 2,
        'Giant Rock Monster': 1,
        'Blizzaster': 3,
        'Comic Hand': 3,
        'Flying Vu Robot': 1,
        '16 Tons': 2,
        'Hands of Doom': 2
    },
    'montoya': {
        'Tentacle Vortex': 1,
        'Doomsday Quack': null,
        'B Movie Monster': null,
        'Dance Shoes': 2,
        'Giant Rock Monster': null,
        'Comic Hand': 3,
        'Blizzaster': null,
        'Hands of Doom': 1,
        '16 Tons': 1,
        'Flying Vu Robot': 1,
        'Spiders': null,
        'Ancient Curse': null,
        'Mellow Bellow': 1,
        'Hissy Fit': null,
        'Not in Kansas': 1,
        'Plant Monster': 1,
        'Shield Buster': 2,
        'Disco Twister': null,
        'Building Portal': 2,
        'Electric Deity': 1,
        'Shrink Ray': null,
        'Magnetism': 2,
        'Zest from Above': 2,
        'Fishaster': 1
    },
    'ringinpitu': {
        'Doomsday Quack': 1,
        'Tentacle Vortex': 6,
        'B Movie Monster': 2,
        'Giant Rock Monster': 4,
        'Dance Shoes': 2,
        'Hands of Doom': 6,
        '16 Tons': 6,
        'Flying Vu Robot': 3,
        'Comic Hand': 7,
        'Blizzaster': 4,
        'Spiders': 3,
        'Ancient Curse': 3,
        'Mellow Bellow': 7,
        'Hissy Fit': 2,
        'Not in Kansas': 3,
        'Plant Monster': 7,
        'Disco Twister': 2,
        'Shield Buster': 2,
        'Building Portal': 6,
        'Electric Deity': 2,
        'Shrink Ray': 4,
        'Fishaster': 3,
        'Magnetism': 9,
        'Zest from Above': 4
    },
    'irian': {
        'Giant Rock Monster': null,
        'Dance Shoes': 1,
        '16 Tons': 1,
        'Flying Vu Robot': 1,
        'Hands of Doom': 1,
        'Blizzaster': 1,
        'Comic Hand': 5,
        'Doomsday Quack': 5,
        'Tentacle Vortex': 3,
        'B Movie Monster': 2,
        'Electric Deity': null,
        'Building Portal': 1,
        'Shrink Ray': 1,
        'Fishaster': 1,
        'Magnetism': 4,
        'Zest from Above': 2,
        'Spiders': null,
        'Mellow Bellow': 6,
        'Ancient Curse': 3,
        'Not in Kansas': 2,
        'Plant Monster': 1,
        'Hissy Fit': 2,
        'Disco Twister': 1,
        'Shield Buster': 2
    },
    'son': {
        'Ancient Curse': 1,
        'Mellow Bellow': 4,
        'Spiders': 1,
        'Disco Twister': 1,
        'Shield Buster': 2,
        'Hissy Fit': 1,
        'Plant Monster': 3,
        'Not in Kansas': 2,
        'Shrink Ray': 1,
        'Building Portal': 1,
        'Electric Deity': 1,
        'Fishaster': 1,
        'Zest from Above': 2,
        'Magnetism': 3,
        'Doomsday Quack': null,
        'Tentacle Vortex': 2,
        'B Movie Monster': 1,
        'Giant Rock Monster': 2,
        'Dance Shoes': null,
        'Hands of Doom': 2,
        '16 Tons': 1,
        'Flying Vu Robot': 2,
        'Comic Hand': 4,
        'Blizzaster': 3
    },
    'kevvineon': {
        'Not in Kansas': 4,
        'Plant Monster': 3,
        'Hissy Fit': 4,
        'Shield Buster': 4,
        'Disco Twister': 3,
        'Spiders': 3,
        'Mellow Bellow': 6,
        'Ancient Curse': 3,
        'Magnetism': 6,
        'Zest from Above': 4,
        'Fishaster': 1,
        'Electric Deity': 3,
        'Building Portal': 1,
        'Shrink Ray': 3,
        'B Movie Monster': 4,
        'Tentacle Vortex': 2,
        'Doomsday Quack': null,
        'Blizzaster': 6,
        'Comic Hand': 6,
        'Flying Vu Robot': 3,
        '16 Tons': 4,
        'Hands of Doom': 4,
        'Dance Shoes': null,
        'Giant Rock Monster': 3
    },
    'laugh tale': {
        'B Movie Monster': 2,
        'Tentacle Vortex': 1,
        'Doomsday Quack': 2,
        'Blizzaster': 1,
        'Comic Hand': 4,
        '16 Tons': 1,
        'Flying Vu Robot': 2,
        'Hands of Doom': 2,
        'Dance Shoes': 1,
        'Giant Rock Monster': 1,
        'Not in Kansas': null,
        'Plant Monster': 1,
        'Hissy Fit': 2,
        'Disco Twister': 1,
        'Shield Buster': 2,
        'Spiders': 1,
        'Mellow Bellow': 4,
        'Ancient Curse': 1,
        'Magnetism': 3,
        'Zest from Above': 1,
        'Fishaster': 1,
        'Electric Deity': 1,
        'Building Portal': 1,
        'Shrink Ray': 1
    },
    'grimm': {
        'Hissy Fit': 5,
        'Plant Monster': 6,
        'Not in Kansas': 5,
        'Disco Twister': 4,
        'Shield Buster': 4,
        'Spiders': 5,
        'Ancient Curse': 4,
        'Mellow Bellow': 8,
        'Magnetism': 8,
        'Zest from Above': 6,
        'Fishaster': 5,
        'Building Portal': 5,
        'Electric Deity': 4,
        'Shrink Ray': 5,
        'B Movie Monster': 5,
        'Tentacle Vortex': 6,
        'Doomsday Quack': null,
        'Comic Hand': 7,
        'Blizzaster': 6,
        'Hands of Doom': 6,
        'Flying Vu Robot': 4,
        '16 Tons': 6,
        'Dance Shoes': null,
        'Giant Rock Monster': 5
    },
    'utopya': {
        'B Movie Monster': 1,
        'Doomsday Quack': 1,
        'Tentacle Vortex': 3,
        'Flying Vu Robot': 1,
        '16 Tons': 3,
        'Hands of Doom': 3,
        'Blizzaster': null,
        'Comic Hand': 3,
        'Giant Rock Monster': 2,
        'Dance Shoes': 1,
        'Plant Monster': 3,
        'Not in Kansas': 2,
        'Hissy Fit': null,
        'Shield Buster': null,
        'Disco Twister': 1,
        'Spiders': null,
        'Mellow Bellow': 1,
        'Ancient Curse': null,
        'Fishaster': null,
        'Magnetism': 3,
        'Zest from Above': 1,
        'Electric Deity': 1,
        'Building Portal': 2,
        'Shrink Ray': 2
    },
    'studio': {
        'Zest from Above': 4,
        'Magnetism': 3,
        'Fishaster': 2,
        'Shrink Ray': 2,
        'Electric Deity': 1,
        'Building Portal': 4,
        'Disco Twister': 2,
        'Shield Buster': 3,
        'Not in Kansas': 2,
        'Plant Monster': 3,
        'Hissy Fit': 3,
        'Mellow Bellow': 5,
        'Ancient Curse': 3,
        'Spiders': 3,
        'Blizzaster': 4,
        'Comic Hand': 3,
        '16 Tons': 6,
        'Flying Vu Robot': 2,
        'Hands of Doom': 4,
        'Dance Shoes': 2,
        'Giant Rock Monster': 2,
        'B Movie Monster': 4,
        'Tentacle Vortex': 4
    },
    'grandma': {
        'Magnetism': 5,
        'Zest from Above': 3,
        'Fishaster': 3,
        'Building Portal': 3,
        'Electric Deity': 1,
        'Shrink Ray': 3,
        'Hissy Fit': 3,
        'Plant Monster': 3,
        'Not in Kansas': 3,
        'Shield Buster': 3,
        'Disco Twister': 2,
        'Spiders': 1,
        'Ancient Curse': 2,
        'Mellow Bellow': 6,
        'Comic Hand': 6,
        'Blizzaster': 4,
        'Hands of Doom': 3,
        '16 Tons': 4,
        'Flying Vu Robot': 2,
        'Dance Shoes': 2,
        'Giant Rock Monster': 2,
        'B Movie Monster': 3,
        'Tentacle Vortex': 4,
        'Doomsday Quack': 1
    },
    'janitra': {
        'B Movie Monster': 2,
        'Tentacle Vortex': 2,
        'Doomsday Quack': null,
        'Comic Hand': 4,
        'Blizzaster': 1,
        'Hands of Doom': 2,
        '16 Tons': 4,
        'Flying Vu Robot': 3,
        'Dance Shoes': 6,
        'Giant Rock Monster': 1,
        'Shield Buster': 3,
        'Disco Twister': null,
        'Hissy Fit': 2,
        'Not in Kansas': 1,
        'Plant Monster': 4,
        'Ancient Curse': 1,
        'Mellow Bellow': 3,
        'Spiders': 2,
        'Zest from Above': 3,
        'Magnetism': 5,
        'Fishaster': 2,
        'Shrink Ray': 2,
        'Building Portal': 3,
        'Electric Deity': 1
    }
}
